import { makeStyles } from "@mui/styles";
import BackgroundGradient from "../../Assets/images/background_gradient.png";

const useStyles = makeStyles((theme) => ({
  header: {
    width: "99%",
    height: "8%",
    borderRadius: "0px 0px 10px 10px",
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.3)",
    top: "0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  header_left: {
    width: "5%",
    height: "100%",
    marginRight: "0%",
  },
  header_mid: {
    width: "20%",
    height: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  recharge_btn: {
    width: "50%",
    height: "30px",
    backgroundColor: "#000000",
    color: "#ffffff",
    borderRadius: "30px",
    "&:hover": {
      backgroundColor: "#535353",
    },
  },
  profile_icon: {
    width: "30px",
    height: "30px",
  },
  logout_button: {
    width: "5px",
  },
  logout_icon: {
    width: "30px",
    height: "30px",
  },
  header_right: {
    width: "5%",
    height: "100%",
    marginLeft: "0%",
  },
  window: {
    width: "100%",
    border: "1px solid white",
    height: "100%",
    position: "relative",
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: "15px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    "& .swiper-button-prev": {
      background: theme.palette.secondary.main,
      padding: "2rem",
      borderRadius: "50%",
      fontSize: "14px",
      color: "#fff",
      "&:hover": {
        background: theme.palette.secondary.light,
      },
    },
    "& .swiper-button-next": {
      background: theme.palette.secondary.main,
      padding: "2rem",
      borderRadius: "50%",
      fontSize: "14px",
      color: "#fff",
      "&:hover": {
        background: theme.palette.secondary.light,
      },
    },
    "& .swiper-button-prev:after": {
      fontSize: "2rem",
    },
    "& .swiper-button-next:after": {
      fontSize: "2rem",
    },
  },
  img: {
    width: "100%",
    height: "100%",
    borderRadius: "15px",
  },
  buttons: {
    width: "100%",
    position: "absolute",
    bottom: 20,
    left: 0,
    zIndex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  phoneBtn: {
    padding: 12,
    background: theme.palette.secondary.main,
    color: "white",
    "&:hover": {
      background: theme.palette.secondary.light,
    },
  },
  videoBtn: {
    padding: 12,
    background: theme.palette.secondary.main,
    color: "white",
    "&:hover": {
      background: theme.palette.secondary.light,
    },
  },
  messageBtn: {
    padding: 12,
    background: theme.palette.secondary.main,
    color: "white",
    "&:hover": {
      background: theme.palette.secondary.light,
    },
  },
  paper: {
    maxWidth: 400,
    maxHeight: 400,
    height: 320,
    bottom: 2,
    right: 72,
    overflow: "hidden",
    position: "fixed",
    backgroundImage: `url(${BackgroundGradient})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "Montserrat, sans-serif",
    zIndex: 1,
  },
  msg_window: {
    width: "108%",
    height: "100%",
    borderRadius: "15px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  incoming_container: {
    height: "100%",
    overflow: "auto",
    overflowY: "scroll",
    "&::-webkit-scrollbar": {
      width: "12px",
    },
    "&::-webkit-scrollbar-track": {
      background: "rgba(255,255,255,0.2)",
      borderRadius: "10px",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255,255,255,0.3)",
      borderRadius: "10px",
      height: "50%",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255,255,255,1)",
    },
  },
  outgo_msg: {
    width: "100%",
    display: "flex",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "end",
    marginTop: theme.spacing(2),
  },
  incoming_msg: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "start",
    marginTop: theme.spacing(2),
  },
  single_image: {
    width: "40px",
    height: "40px",
    backgroundColor: "rgba(255,255,255,0.4)",
    borderRadius: "200px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  outgo_text_box: {
    width: "70%",
    height: "100%",
    marginLeft: "auto",
    marginRight: "10px",
    borderRadius: "10px",
    backgroundColor: "rgba(255,255,255,0.3)",
    textAlign: "left",
    padding: theme.spacing(1),
  },
  incoming_text_box: {
    width: "70%",
    height: "100%",
    marginLeft: "10px",
    marginRight: "auto",
    borderRadius: "10px",
    backgroundColor: "rgba(255,255,255,0.3)",
    textAlign: "left",
    padding: theme.spacing(1),
  },
  outgoing_text: {
    color: "rgba(0,0,0,0.4)",
    fontSize: "16px",
  },
  incoming_text: {
    color: "rgba(0,0,0,0.7)",
    fontSize: "16px",
  },
  outgoing_msg: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "end",
    marginTop: theme.spacing(2),
  },
  outgoing_text_box: {
    color: "black",
    width: "70%",
    height: "100%",
    marginLeft: "auto",
    marginRight: "10px",
    borderRadius: "10px",
    border: "none",
    backgroundColor: "rgba(255,255,255,0.3)",
    textAlign: "right",
    padding: theme.spacing(1),
    "&:focus": {
      outline: "none",
    },
  },
  box_single_user_history: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: theme.spacing(1),
  },
  avatar_box: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  history_name: {
    color: "black",
    fontSize: "14px",
    fontWeight: "bold",
  },
  history_lastseen: {
    color: "black",
    fontSize: "12px",
  },
  history_actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
  },
  history_actions_icons: {
    width: "14px",
    height: "14px",
    marginLeft: theme.spacing(1),
  },
  single_user_history_text: {
    marginLeft: theme.spacing(1),
  },
  root: {
    "& .MuiPaper-root": {
      backgroundImage: `url(${BackgroundGradient})`,
      backgroundSize: "cover",
      backgroundPosition: "center",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      fontFamily: "Montserrat, sans-serif",
    },
  },
  acceptCallBtn: {
    color: "white",
    backgroundColor: "green",
    padding: 12,
  },
  rejectCallBtn: {
    color: "white",
    backgroundColor: "red",
    padding: 12,
  },
}));

export default useStyles;
